version: "4.24.2"
services:
  app:  
    build: .
    ports:
      - "5000:5000" 
    links:
      - mongoSDK 
  mongoSDK:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Jefferson10  
      - MONGO_INITDB_ROOT_PASSWORD=alex123 